//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.11-2021/01/28-beta
`include "./includes/proj_verilog/sp_verilog.vh" //_\SV

   // Included URL: "https://raw.githubusercontent.com/mayank-kabra2001/WARPV-TSMC/main/warpv.tlv"// Included URL: "https://raw.githubusercontent.com/stevehoover/warp-v_includes/1d1023ccf8e7b0a8cf8e8fc4f0a823ebb61008e3/risc-v_defs.tlv"
     
//_\SV
   module alu(
       input clk,
       input reset,
       input [31:0] reg_value1, 
       input [31:0] reg_value2,
       input [31:2]raw_i_imm,
       input raw_funct7_5, 
       input valid_exe, 
       output reg [31:0] addi_rslt,
       output reg [31:0] add_rslt,
       output reg [31:0] sub_rslt);
      
`include "adder_gen.v"
generate //_\TLV
   //_\source /raw.githubusercontent.com/mayankkabra2001/WARPVTSMC/main/warpv.tlv 4038   // Instantiated from adder.tlv, 19 as: m4+adder() 
      assign L0_reg_value1_a0 = reg_value1; 
      assign L0_reg_value2_a0 = reg_value2; 
      assign L0_raw_i_imm_a0 = raw_i_imm; 
      assign L0_raw_funct7_5_a0 = raw_funct7_5;
      assign L0_valid_exe_a0 = valid_exe; 
      `BOGUS_USE(L0_valid_exe_a0)
      //?$valid_exe
      assign L0_addi_rslt_a0[31:0]  = L0_reg_value1_a0 + L0_raw_i_imm_a0;  // TODO: This has its own adder; could share w/ add/sub.
      assign L0_add_sub_rslt_a0[31:0] = (L0_raw_funct7_5_a0 == 1) ?  L0_reg_value1_a0 - L0_reg_value2_a0 : L0_reg_value1_a0 + L0_reg_value2_a0;
      assign L0_add_rslt_a0[31:0]   = L0_add_sub_rslt_a0;
      assign L0_sub_rslt_a0[31:0]   = L0_add_sub_rslt_a0;
      
      always@(L0_addi_rslt_a0) addi_rslt = L0_addi_rslt_a0;
      always@(L0_add_rslt_a0) add_rslt = L0_add_rslt_a0;
      always@(L0_sub_rslt_a0) sub_rslt = L0_sub_rslt_a0;
   //_\end_source 
endgenerate

//_\SV
   endmodule

