// Generated by SandPiper(TM) 1.11-2021/01/28-beta from Redwood EDA.
// Redwood EDA does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "./includes/sandpiper_gen.vh"






//
// Signals declared top-level.
//

// For $add_rslt.
wire [31:0] L0_add_rslt_a0;

// For $add_sub_rslt.
wire [31:0] L0_add_sub_rslt_a0;

// For $addi_rslt.
wire [31:0] L0_addi_rslt_a0;

// For $raw_funct7_5.
wire L0_raw_funct7_5_a0;

// For $raw_i_imm.
wire L0_raw_i_imm_a0;

// For $reg_value1.
wire L0_reg_value1_a0;

// For $reg_value2.
wire L0_reg_value2_a0;

// For $sub_rslt.
wire [31:0] L0_sub_rslt_a0;

// For $valid_exe.
wire L0_valid_exe_a0;


